### ISSUE TITLE
Review of module 2: Staging your project

### ISSUE THREAD

**Issue by thessaly** [ohwmakers/OHM-curriculum#30]

**Comment by thessaly** [comment]
### Do you agree with the content?
Yes

### Do you agree with the opinions/statements
Yes

### Any content to add/remove?
#### Home
- I'd remove references to the canvas here, basically replace 1st paragraph with:
> As part of this module you will learn what is the scope your project and why it's important to define it; you will hear about the different types of projects based on their relation to existent ones, and we will guide you through the building blocks you need to consider, with a focus in your project home.

#### 2.1 "Defining your project"
- I'd change the bullets for numbers, as later on I refer to the questions with numbering

#### 2.2 "Working smart"

#### 2.3 "Building blocks overview"
- I'd add a closing paragraph to the "The minimum you need to get there" section, something like this:
> Think of the necessary materials and steps you need to follow, to achieve that minimum piece of work that satisfies the goal you defined in the previous module.

#### 2.4 "First impressions matter"
Nothing to add

### Any more resources?
#### For 2.1
- [The project triangle](https://www.youtube.com/watch?v=YOkOPN7EcuQ&t=1s)
- [Setting SMART goals](https://www.mindtools.com/pages/article/smart-goals.htm)
- [Definition of Output, Outcome and Impact with Examples](https://analyticsinaction.co/definition-output-outcome-impact-with-examples)

#### For 2.2
- [Reinventing the Wheel - Wikipedia entry](https://en.wikipedia.org/wiki/Reinventing_the_wheel)
- [When reinventing the wheel does make sense](https://hackaday.com/2021/05/08/reinventing-the-wheel/)

#### For 2.3
- [Overview of the Various Types of Hardware Prototypes](https://www.hackster.io/news/overview-of-the-various-types-of-hardware-prototypes-60d33d92e3a3)
- [OSHWA - Best practices for Open source Hardware 1.0](https://www.oshwa.org/sharing-best-practices/)

#### For 2.4
Can't think of any others

### Are the assignments appropriate
#### For 2.1
Yes, I think it makes sense. I'd only replace the sample statement with an example closer to open hardware (this was Mozilla's example), and make sure to highlight/colour the key parts in the statement skeleton

#### For 2.2
Yes, I think this is a good assignment.

#### For 2.3
Yes, makes sense, they go back to the canvas and review. Also documenting prototypes ideas is good for fostering doc practice.

#### For 2.4
Feels natural to ask them to draft a home page, it will help them decant ideas about their goals also.

### Typos 
#### For 2.1
- > In the introduction we already mentioned some terms that **we** will be detailing more now. 
- > For example**:** you may be **developing** an environmental monitoring tool**,** but is the goal of the **device** to produce air quality data or air quality and water quality data? 
- > Finally, question 4 asks about your motivation to work on this project**. It makes** you think of what would be different **in the world** if your project already existed.

#### For 2.2
Couldn't find any

#### For 2.3
> Software and firmware: if your project needs code to run, **include** the source, dependencies, version and state (stable or not?).

#### For 2.4
> This is another advantage of making web pages with GitHub/GitLab: you can easily **update the website** just by modifying the README or source file.

**Comment by vektorious** [comment]
Fixed everything in PR #40

### Do you agree with the content?
Yes

### Do you agree with the opinions/statements

Yes

### Any content to add/remove?
#### Home
>     * I'd remove references to the canvas here, basically replace 1st paragraph with:
> > As part of this module you will learn what is the scope your project and why it's important to define it; you will hear about the different types of projects based on their relation to existent ones, and we will guide you through the building blocks you need to consider, with a focus in your project home.

- I agree to remove the Canvas reference but don't understand what you want to say with "with a focus on your project home".
- I removed the reference and wrote:
> As part of this module you will learn how to scope your project and why it's important to define it. You will hear about the different types of projects based on their relation to existing ones. We will guide you through the various building blocks you need to consider for building your open hardware project.

#### 2.1 "Defining your project"
>     * I'd change the bullets for numbers, as later on I refer to the questions with numbering
- fixed that
- I changed in summary "Delimit the scope" to "Define the scope" because I think define is more common language
- changed delimiting > defining also in the text.
- changed ... detailing now > we will discuss in detail now (simpler language?)
- wrote and between "device to produce air quality data or air quality AND water quality data" in caps
 
#### 2.2 "Working smart"
- nothing from my side

#### 2.3 "Building blocks overview"
>     * I'd add a closing paragraph to the "The minimum you need to get there" section, something like this:

> > Think of the necessary materials and steps you need to follow, to achieve that minimum piece of work that satisfies the goal you defined in the previous module.

- doesn't hurt, added the sentence

#### 2.4 "First impressions matter"
- nothing to add/remove from my side

### Any more resources?
#### For 2.1
> 
>     * [The project triangle](https://www.youtube.com/watch?v=YOkOPN7EcuQ&t=1s)
> 
>     * [Setting SMART goals](https://www.mindtools.com/pages/article/smart-goals.htm)
> 
>     * [Definition of Output, Outcome and Impact with Examples](https://analyticsinaction.co/definition-output-outcome-impact-with-examples)
- added them

#### For 2.2

>     * [Reinventing the Wheel - Wikipedia entry](https://en.wikipedia.org/wiki/Reinventing_the_wheel)
>     * [When reinventing the wheel does make sense](https://hackaday.com/2021/05/08/reinventing-the-wheel/)
- added them

#### For 2.3
>     * [Overview of the Various Types of Hardware Prototypes](https://www.hackster.io/news/overview-of-the-various-types-of-hardware-prototypes-60d33d92e3a3)
>     * [OSHWA - Best practices for Open source Hardware 1.0](https://www.oshwa.org/sharing-best-practices/)
- added them

#### For 2.4
- well, let's see what feedback we get. I guess building webpages is not easy for everyone

### Are the assignments appropriate
#### For 2.1

> Yes, I think it makes sense. I'd only replace the sample statement with an example closer to open hardware (this was Mozilla's example), and make sure to highlight/colour the key parts in the statement skeleton
- I changed the example statement: I’m working with plant scientists in Boston to develop a remote sensor to measure plant water content, so it can be used in areas with water shortage to efficiently water crop plants to sustain supply of drinking water and food.

#### For 2.2

#### For 2.3
> Yes, makes sense, they go back to the canvas and review. Also documenting prototypes ideas is good for fostering doc practice.
- I strongly agree

#### For 2.4
> Feels natural to ask them to draft a home page, it will help them decant ideas about their goals also.
I agree

### Typos
#### For 2.1

> In the introduction we already mentioned some terms that **we** will be detailing more now.
> For example**:** you may be **developing** an environmental monitoring tool**,** but is the goal of the **device** to produce air quality data or air quality and water quality data?
> Finally, question 4 asks about your motivation to work on this project**. It makes** you think of what would be different **in the world** if your project already existed.
- fixed them

#### For 2.2
- Most derivatives are more *or* less copies of the original

#### For 2.3
> Software and firmware: if your project needs code to run, **include** the source, dependencies, version and state (stable or not?).
- fixed
- broad idea about what open hardware **is**

#### For 2.4
> This is another advantage of making web pages with GitHub/GitLab: you can easily **update the website** just by modifying the README or source file.
- fixed that
