### ISSUE TITLE
Review of module 5: roadmapping

### ISSUE THREAD

**Issue by thessaly** [ohwmakers/OHM-curriculum#33]

**Comment by amchagas** [comment]
Changed the approach to filling this issue a bit:

Since we are working on branches, all changes will be highlighted on the comparison system here on GitHub. So changes are being implemented directly on the branch, with pointers on the issue to what was done:

###Common changes to all subunits:
- A lot of the roadmap "literature" is based on company/product examples. Although not exactly what we wanted, I added more resources comming from this area/space, and indicated that on the resource link. The reason for it is that I think it will be useful for people to have the text/content about this, even if it comes from a company/product development perspective.
- removed work in progress banners

### 5.1:
- Fixed typos.
- Added resources

### 5.2:
- added text for "Assessing progress and monitor indicators" section
- fixed typos

#### Suggestion: Change order of "Assessing progress and monitor indicators" and "Tools for planning progress"

### 5.3:
- added text for "tips and tools"
- added resources

#### Suggestion: not sure that assigment  for this subunit (Think of contributors' pathways for your project) is aligned with the majority of its content. I understand how it is very related to time management, but seems more like something for module 7?

### 5.4:
no major changes
