### ISSUE TITLE
Review of module 6: licenses & standards

### ISSUE THREAD

**Issue by thessaly** [ohwmakers/OHM-curriculum#34]

**Comment by vektorious** [comment]
## MAIN
### Do you agree with the content?
Yes

### Do you agree with the opinions/statements
Yes

### Any content to add/remove?
I removed the comment. I guess we don't need it anymore. The text was also doubled. I removed what (I think) was the previous version.

### Any assignments to add/remove
No

### Any resources to add/remove?
No

**Comment by vektorious** [comment]
## 6.1 How licenses work
### Do you agree with the content?
Yes - it's a lot of (nice) text and backstory. It might be long to read but it's interesting and it was fun to read (even although I knew the 3D-printer story)
I feel like we have the 3D-printer story as an example somewhere else as well but couldn't find it when I was looking for it.
EDIT: Found it. It's in module 1.2 brief history of OH. But it just introduces RepRap so that's fine.

### Do you agree with the opinions/statements
Yes

### Any content to add/remove?
I removed the comment. I guess we don't need it anymore.

### Any assignments to add/remove
No

### Any resources to add/remove?
No

**Comment by vektorious** [comment]
## 6.2 Open Hardware Licenses
### Do you agree with the content?
Yes

### Do you agree with the opinions/statements
Yes

### Any content to add/remove?
No

### Any assignments to add/remove
No

### Any resources to add/remove?
No

**Comment by vektorious** [comment]
## 6.3 Documentation Standards
### Do you agree with the content?
Yes

### Do you agree with the opinions/statements
Yes

### Any content to add/remove?
- Do we need the first bullet points or did you just leave them there from when you were working on this module @amchagas ?
>   - The importance of standards (compatibility, reproducibility, repairability, guideline)  
>  - What is a suitable standard for my project?
>  - Examples of open standards and how to apply them to your project (eg DIN spec)
>  - What are the standards in your region? (Europe CE, Brazil INMETRO, etc)

- I'm not sure if we should talk more about the content of the OSHWA standards. For now, it's fine, I guess.


### Any assignments to add/remove
No

### Any resources to add/remove?
No

**Comment by vektorious** [comment]
## 6.4 Findability
### Do you agree with the content?
Yes

### Do you agree with the opinions/statements
Yes

### Any content to add/remove?
You benefit from a transitional sentence between the last paragraph and the assignments. But for now it's fine.

### Any assignments to add/remove
No

### Any resources to add/remove?
No

**Comment by amchagas** [comment]
Just reviewed the comments and added changes as a commit
