### ISSUE TITLE
Review of module 7: community & comms

### ISSUE THREAD

**Issue by thessaly** [ohwmakers/OHM-curriculum#35]

**Comment by amchagas** [comment]
**Do you agree with the content?**

**Do you agree with the opinions/statements**

All modules: yes!


**Any content to add/remove?**

All modules: no, made minor changes in wording on some phrases (will be highlighted on the pull request)

**Any more resources?**

7.3 is missing a link to a video mentioned in the text @thessaly I tried finding it from the text description, but couldn't. Could you please check this one out? it is in **Intro to Communications (a.k.a. Comms)** sub section


**Are the assignments appropriate**
yes

**Typos**
fixed in text. Highlighted on pull request

**Comment by vektorious** [comment]
I found the video and added it ;)
